baseURL = "https://lumostone.com/"
languageCode = "en-us"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

[languages]
  [languages.en]
    contentDir = "content/posts/en"
    title = "lumostone"
    languageName = "English"
    weight = 1
  [languages.zh-tw]
    contentDir = "content/posts/zh-tw"
    title = "lumostone"
    languageName = "繁體中文"
    weight = 2

[module]
  [[module.imports]]
    path = "github.com/lumostone/hugo-theme-lumostone"

[author]
  name = "lumostone"

[params]
  enableSummary = true
  smartToc = true

[markup]
  [markup.highlight]
    style = "monokailight"
