baseURL = "https://lumostone.com/"
languageCode = "en-us"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

googleAnalytics = "G-T9LBVECNMJ"

[languages]
  [languages.en]
    contentDir = "content/en/posts"
    title = "lumostone"
    languageName = "English"
    weight = 1
  [languages.zh-tw]
    contentDir = "content/zh-tw/posts"
    title = "lumostone"
    languageName = "繁體中文"
    weight = 2

[module]
  [[module.imports]]
    path = "github.com/lumostone/hugo-theme-lumostone"

[author]
  name = "lumostone"

[params]
  enableSummary = true
  smartToc = true
  footer = [{ url = "https://github.com/lumostone/lumostone.github.io", text = "Source code hosted on Github." }]

[markup]
  [markup.highlight]
    style = "monokailight"

[social]
  github = "https://github.com/lumostone"
