baseURL = "https://lumostone.com/"
languageCode = "en-us"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

[languages]
  [languages.en]
    contentDir = "content/en"
    title = "lumostone"
    languageName = "English"
    weight = 1
  [languages.zh-tw]
    contentDir = "content/zh-tw"
    title = "lumostone"
    languageName = "繁體中文"
    weight = 2

[module]
  [[module.imports]]
    path = "github.com/spf13/hyde"
